describe('Visitando demoblaze', () => {

  it('Deberia Agregar dos productos al carrito', () => {
    cy.visit('https://www.demoblaze.com/')
    cy.contains('Samsung galaxy s6').click()
    cy.contains('Add to cart').click()
    cy.contains('Home').click()
    cy.contains('Nokia lumia 1520').click()
    cy.contains('Add to cart').click()
  })

  it('Deberia Visualizar carrito y verificar que existan los productos seleccionados', () => {
    cy.visit('https://www.demoblaze.com/')
    cy.contains('Samsung galaxy s6').click()
    cy.contains('Add to cart').click()
    cy.contains('Home').click()
    cy.contains('Nokia lumia 1520').click()
    cy.contains('Add to cart').click()
    cy.contains('Cart').click()
    cy.contains('Samsung galaxy s6')
    cy.contains('Nokia lumia 1520')
  })

  it('Deberia completar el formulario de compra', () => {
    cy.visit('https://www.demoblaze.com/')
    cy.contains('Samsung galaxy s6').click()
    cy.contains('Add to cart').click()
    cy.contains('Home').click()
    cy.contains('Nokia lumia 1520').click()
    cy.contains('Add to cart').click()
    cy.contains('Cart').click()
    cy.contains('Samsung galaxy s6')
    cy.contains('Nokia lumia 1520')
    cy.contains('Place Order')
    cy.contains('Place Order').click()
    cy.get('#name').type('Luis')
    cy.get('#country').type('Venezuela')
    cy.get('#city').type('Coro')
    cy.get('#card').type('123123123123')
    cy.get('#month').type('12')
    cy.get('#year').type('2025')
  })

  it('Deberia finalizar la compra', () => {
    cy.visit('https://www.demoblaze.com/')
    cy.contains('Samsung galaxy s6').click()
    cy.contains('Add to cart').click()
    cy.contains('Home').click()
    cy.contains('Nokia lumia 1520').click()
    cy.contains('Add to cart').click()
    cy.contains('Cart').click()
    cy.contains('Samsung galaxy s6')
    cy.contains('Nokia lumia 1520')
    cy.contains('Place Order')
    cy.contains('Place Order').click()
    cy.get('#name').type('Luis')
    cy.get('#country').type('Venezuela')
    cy.get('#city').type('Coro')
    cy.get('#card').type('123123123123')
    cy.get('#month').type('12')
    cy.get('#year').type('2025')
    cy.contains('Purchase').click()
    cy.contains('Thank you for your purchase!')
  })
})